name: alic
description: "A little image compressor"
publish_to: "none"
version: 1.3.1+24

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  window_manager: ^0.3.8
  rust_builder:
    path: rust_builder
  flutter_rust_bridge: 2.0.0-dev.39
  file_selector: ^1.0.3
  signals: ^5.0.0
  open_file_macos: ^0.0.1
  data_table_2: ^2.5.10
  super_drag_and_drop: ^0.8.4
  path: ^1.8.3
  super_clipboard: ^0.8.4
  icons_launcher: ^2.1.7
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  package_info_plus: ^8.0.0
  http: ^1.2.1
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  signals_lint: ^5.0.0
  freezed: ^2.4.7
  flutter_lints: ^4.0.0
  integration_test:
    sdk: flutter
  build_runner: ^2.4.9
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

icons_launcher:
  image_path: "assets/alic-logo.png"
  platforms:
    macos:
      enable: true
