name: alic
description: "A little image compressor"
publish_to: "none"
version: 1.0.1+14

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  window_manager: ^0.3.8
  rust_builder:
    path: rust_builder
  flutter_rust_bridge: 2.0.0-dev.22
  file_selector: ^1.0.3
  signals: ^4.0.2
  open_file_macos: ^0.0.1
  data_table_2: ^2.5.10
  super_drag_and_drop: ^0.8.4
  path: ^1.8.3
  super_clipboard: ^0.8.4
  icons_launcher: ^2.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

icons_launcher:
  image_path: "assets/alic-logo.png"
  platforms:
    macos:
      enable: true
