[package]
name = "rust_lib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.0.0"
image = "^0.25"
libcaesium = { git = "https://github.com/Lymphatus/libcaesium.git", tag = "0.15.5" }
